version: "2"
#virtualmachines:
#- name: kubernetes
#  image: instruqt/kubernetes-110
#  machine_type: n1-standard-1
#  ports:
#  - 8001
#  shell: /bin/bash
#  pool_size: 1
containers:
- name: kubernetes
  image: alpine
  ports: []
  shell: /bin/bash
